name: Feature Request
description: Suggest an idea or enhancement
title: "[FEATURE]: "
labels: ["✨ | Enhancement"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before proceeding
      options:
        - label: I am using the latest version of the project
          required: true
        - label: I have checked that this feature request hasn't been suggested before
          required: true
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Provide a clear and concise description of the feature you'd like to see.
      placeholder: I would like to see...
    validations:
      required: true
  - type: textarea
    id: problem-solution
    attributes:
      label: Problem and Solution
      description: Describe the problem this feature would solve or how it would improve the project.
      placeholder: This feature would help with...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: I've also thought about...
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mock-ups about the feature request here.
      placeholder: Potential challenges in implementation might include...
    validations:
      required: false
